### ISSUE TITLE
请教一下，ssr-with-ts 在 config.ssr.js 引入一个配置文件后，csr 打开空白，ssr没问题。

### ISSUE THREAD

**Issue by JohannLai** [ykfe/egg-react-ssr#109]
可能是我的打开方式不对，复现 demo 如下，麻烦帮忙看看～ 感谢🙏

https://github.com/JohannLai/ssr-with-ts/commit/00f32189dc3e4978cbb1950d0cf450606bda9825

还增加了这个 文件https://github.com/JohannLai/ssr-with-ts/blob/master/config/config.default.js

原意是想在 page 底下写路由文件，然后引用整理放到 config.ssr.js 中，使到页面和路由不分开

**Comment by zhangyuang** [comment]
不要在config.ssr.js文件中去引用ts文件。运行时并不支持解析ts文件

**Comment by JohannLai** [comment]
好的，感谢 @zhangyuang

**Comment by zhangyuang** [comment]
请问你是要用我们这套方案开发线上项目吗

**Comment by JohannLai** [comment]
@zhangyuang 对，马上就要上线了

**Comment by zhangyuang** [comment]
可以扫码进入dingding群详聊，我们可以随时提供技术支持。麻烦上线后通知一下我们，可以把你们的应用加入我们的readme当中

**Comment by JohannLai** [comment]
我还没有钉钉欸  😭

**Comment by zhangyuang** [comment]
你微信多少我加你

**Comment by JohannLai** [comment]
> 你微信多少我加你

lzh472040743

**Comment by JohannLai** [comment]
done~
