### ISSUE TITLE
使用mobx的demo时出现些问题

### ISSUE THREAD

**Issue by Yxliam** [ykfe/egg-react-ssr#110]
当我修改mobx的数据时，页面会报错，Uncaught Error: MobX Provider: The set of provided stores has changed，需要手动刷新页面

**Comment by zhangyuang** [comment]
fix by [commit](https://github.com/ykfe/egg-react-ssr/commit/d0279fab60681f635c9cb10c10959d9e53529cad)

**Comment by JohannLai** [comment]
@zhangyuang  原理是什么？ 我发现我也是这样的报错

**Comment by zhangyuang** [comment]
ref: https://stackoverflow.com/questions/45383400/mobx-and-hmr-please-avoid-replacing-stores-as-the-change-might-not-propagate-to

**Comment by JohannLai** [comment]
学习了~

**Comment by zhangyuang** [comment]
报错是解决了，不过修改store的热更新还是有点问题。晚点再看看。有兴趣可以尝试修复贡献PR
