### ISSUE TITLE
请问下，使用axios 请求数据的时候，出现了这个错误

### ISSUE THREAD

**Issue by Yxliam** [ykfe/egg-react-ssr#111]
![image](https://user-images.githubusercontent.com/16329468/69690946-59aad580-1108-11ea-8a12-9877ee8b7967.png)

**Comment by zhangyuang** [comment]
给可复现仓库。。只给这个并不知道你是什么错误

**Comment by Yxliam** [comment]
@zhangyuang mobx的例子只是简单的使用axios调接口，就出现这个问题了

**Comment by zhangyuang** [comment]
并不能复现你所说的问题。提issue请描述详细复现过程
