### ISSUE TITLE
关于第三方库的window.onpopstate，如监控库，优先其他代码加载导致ssr渲染路由回退调用时this指向不正确

### ISSUE THREAD

**Issue by c690554125** [ykfe/egg-react-ssr#116]
arms, fundebug之类的优先加载，代码内部有window.onpopstate = fn，这个注册的方法，会优先于react-router里注册的onpopstate执行，且在getInitialProps方法中会覆盖掉第三方库的onpopstate。

当ssr渲染A页面后，路由进入B页面，点击浏览器回退或调用this.props.history.goBack()，会出现window.onpopstate优先触发，导致路由还没有完全回退到A就开始触发this.getInitialProps()，此时this指向的是B页面，调用的也是已经unmount的B页面的getInitialProps方法。

提供一个简单的解决方案，具体看看官方如何写更优雅。

在getInitialProps.js中修改：

// 开始，外层这里 维护一个this， 维护一个指针不变的调用getIntialProps的方法
`
let thisTarget = null
const popFn = function() {
  if(thisTarget && thisTarget.getInitialProps) {
    thisTarget.getInitialProps()
  }
  window.removeEventListener('popstate', popFn)
}
`

// componentDidMount里改this，换addeventlistener注册pop方法
`
if (window.__USE_SSR__) {
        // 这里 更改this指针
        thisTarget = _this2
       // 用addeventListener方法添加popstate, 晚于 react-router触发路由跳转后调用
        window.addEventListener('popstate', popFn)
}
`

**Comment by zhangyuang** [comment]
看了一下应该得换成addEventListener来绑定，具体怎么写晚点有空看看
pr is welcome

**Comment by c690554125** [comment]
已提交pr
