### ISSUE TITLE
一些页面不需要Layout，怎么配置

### ISSUE THREAD

**Issue by guchenhui** [ykfe/egg-react-ssr#122]

**Comment by zhangyuang** [comment]
不需要layout就commonNode就返回空就行了，注释有写

**Comment by guchenhui** [comment]
@zhangyuang 我的意思大多数页面是需要一个统一的layout，但有个别页面是不需要这个layout的。我怎么最小代码，最合理的满足这个需求？

**Comment by zhangyuang** [comment]
```
const layoutMap = {
'/': true,
'/news': false
}
const path = props.layoutData.req.path
const commonNode = props => (
  props.children
    ? <div className='normal'>{
layoutMap(path) && <h1 className='title'><Link to='/'>Egg + React + SSR</Link><div className='author'>by ykfe</div></h1>}
{props.children}</div>
    : ''
)
```

**Comment by guchenhui** [comment]
@zhangyuang 不行哎。T T

Page.chunk.js:435 Uncaught TypeError: Cannot read property 'req' of undefined
    at commonNode (Page.chunk.js:435)
    at Layout (Page.chunk.js:447)
    at renderWithHooks (getComponent.js:8)
    at mountIndeterminateComponent (getComponent.js:8)
    at beginWork (getComponent.js:8)
    at performUnitOfWork (getComponent.js:8)
    at workLoop (getComponent.js:8)
    at HTMLUnknownElement.callCallback (getComponent.js:8)
    at Object.invokeGuardedCallbackDev (getComponent.js:8)
    at invokeGuardedCallback (getComponent.js:8)

**Comment by zhangyuang** [comment]
我看看，能取到不过在hydrate的时候有些问题

**Comment by zhangyuang** [comment]
const layoutMap = {
  '/': true,
  '/news': false
}

const commonNode = (props) => {
  const path = props => __isBrowser__ ? location.pathname : props.layoutData.path
  return props.children
    ? <div className='normal'>{
layoutMap[path] && <h1 className='title'><Link to='/'>Egg + React + SSR</Link><div className='author'>by ykfe</div></h1>}
{props.children}</div>
    : ''
}

**Comment by guchenhui** [comment]
@zhangyuang 可以了。谢谢。我后面想了想，layoutMap的配置应该放在config.ssr.js会更合理吧。

**Comment by zhangyuang** [comment]
放哪都行，看你想怎么维护

**Comment by guchenhui** [comment]
@zhangyuang     props.layoutData.path拿到的是/news/2 ,并不能拿到/news/:id。有没有办法能拿到/news/:id呢？
