### ISSUE TITLE
yarn project does not start

### ISSUE THREAD

**Issue by gromov-io** [ykfe/egg-react-ssr#136]
PS：我不会说中文，我使用翻译。

几天前在我的笔记本电脑上使用'yk-cli'我为我的项目安装了一个模板，检查一切正常，并把它放在我的存储库中，然后来到办公室，并试图在正常工作的计:

```
git clone <project>
cd <project>
yarn
yarn start
```

所有软件包都已正确安装，但项目未启动
![image](https://user-images.githubusercontent.com/46241127/71320078-8f4c9f80-24b7-11ea-84b8-82cb0c7e3836.png)

该解决方案是在"package*json"中将'npm'重命名为'yarn'的原始重命名"
![image](https://user-images.githubusercontent.com/46241127/71320146-67aa0700-24b8-11ea-9a2b-103f5b2fcd9c.png)

**Comment by zhangyuang** [comment]
you can speak english directly,it's welcome
i use yarn with 1.15.2,it can start app succeed
![image](https://user-images.githubusercontent.com/17424434/71320492-15340f00-24e7-11ea-949e-dcfd3d6e1d3b.png)
