### ISSUE TITLE
Helmet use?

### ISSUE THREAD

**Issue by zanjs** [ykfe/egg-react-ssr#140]
react-helmet ssr

**Comment by zhangyuang** [comment]
no need to use react-helment, you can write html head tag in layout directly

**Comment by zanjs** [comment]
@zhangyuang  Dynamic title, Cannot write directly!

**Comment by zhangyuang** [comment]
you can provide a specific scene，in layout component, you can get serverData and request context and set title dynamic dynamically

**Comment by zanjs** [comment]
@zhangyuang ok! Thank you!
