### ISSUE TITLE
the project is not built without a globally installed yk-cli

### ISSUE THREAD

**Issue by gromov-io** [ykfe/egg-react-ssr#141]
the project is not built without a globally installed yk-cli. And this is a bit strange - since I do not see the point in production to put yk-cli
![image](https://user-images.githubusercontent.com/46241127/71903287-cdfb7e80-3174-11ea-8cb5-3a94ca206269.png)

**Comment by zhangyuang** [comment]
can you provide a reproducible repo?

**Comment by gromov-io** [comment]
hm.. I don't understand what the problem is. I can't reproduce this error right now.  But I can say for sure-it disappeared after installing yk-cli. But the project worked in yarn start mode, but when I tried to do yarn build, everything broke down. I will follow as there will be a little more information-I will unsubscribe to this ticket

**Comment by zhangyuang** [comment]
the problem general cause by there are multiple version react or react-dom in your repo, yk-cli is a dependency in package.json, you must install and use yk-cli package which in your repo node_modules instead of global。
