### ISSUE TITLE
怎么支持ts的同时也支持类似antd中UI的按需加载

### ISSUE THREAD

**Issue by zkeyword** [ykfe/egg-react-ssr#155]
`
const webpackModule = {
  rules: [
    {
      oneOf: [
        {
          test: /\.(js|mjs|jsx|ts|tsx)$/,
          exclude: /node_modules/,
          loader: require.resolve('babel-loader'),
          options: {
            cacheDirectory: true,
            cacheCompression: false,
            presets: [
              [
                '@babel/preset-env',
                {
                  modules: false
                }
              ],
              '@babel/preset-react',
              ['react-app', { 'flow': false, 'typescript': true }]
            ],
            plugins: [
              [
                'import',
                {
                  libraryName: 'antd',
                  libraryDirectory: 'lib',
                  style: 'css'
                }
              ]
            ]
          }
        }
      ]
    }
  ]
}
`

抛出

`2020-02-20 16:22:53,866 ERROR 88216 [-/127.0.0.1/-/162ms GET /] Page Controller renderToStream Error ~/Documents/test/ssrYk/node_modules/antd/lib/style/index.css:7
[0] [0] body {
[0] [0]      ^
[0] [0] 
[0] [0] SyntaxError: Unexpected token '{'`

**Comment by zhangyuang** [comment]
参考ssr-with-antd的webpack配置
