### ISSUE TITLE
example里面multipage的那个prod环境404

### ISSUE THREAD

**Issue by kristyzhangwx** [ykfe/egg-react-ssr#157]
Refused to apply style from 'http://localhost:7001/static/css/vendor.chunk.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
(index):1 GET http://localhost:7001/static/js/runtime~index.js net::ERR_ABORTED 404 (Not Found)
(index):1 Refused to apply style from 'http://localhost:7001/static/css/index.chunk.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
5(index):1 GET http://localhost:7001/static/js/index.chunk.js net::ERR_ABORTED 404 (Not Found)

**Comment by zhangyuang** [comment]
已修复
