### ISSUE TITLE
使用pm2代替egg-scripts后，出现的资源读取失败问题

### ISSUE THREAD

**Issue by herorest** [ykfe/egg-react-ssr#161]

**Comment by herorest** [comment]
首先，这个脚手架本身我很喜欢，很轻量化，也符合我的需要，但是由于公司的要求，上线的node应用均需要以pm2启动，因此采用egg官方提供的方式，在根目录下创建server.js，内容如下：
```javascript
const egg = require('egg');
const workers = Number(process.argv[2] || require('os').cpus().length);
egg.startCluster({
  workers,
  baseDir: __dirname,
});
```

然后通过命令启动

```javascript
npm run build && pm2 start start.js
```

但最后打开页面，却显示
![image](https://user-images.githubusercontent.com/2202767/77025135-4bd8d300-69cb-11ea-8f83-f2654341dd1b.png)

麻烦各位大佬给看看怎么弄？

**Comment by zhangyuang** [comment]
EGG_SERVER_ENV=prod pm2 start server.js

**Comment by herorest** [comment]
ok
