### ISSUE TITLE
官方例子bug 首次加载文章详情退回无法获取news的数据

### ISSUE THREAD

**Issue by wjryours** [ykfe/egg-react-ssr#163]
具体触发的流程
1.安装流程初始化egg-react-ssr
2.启动项目
3.进入到首页，然后点击进入到一个文章的详情
4.刷新页面
5.这时候点击浏览器的回退按钮退回到首页(ps:并不是点击a这种链接跳转到首页)
6.发现无法获取news
请问这种应该如何解决

**Comment by zhangyuang** [comment]
等会看看

**Comment by zhangyuang** [comment]
fixed by [ykfe-utils@3.6.4](https://github.com/ykfe/egg-react-ssr/commit/c03e1c92769f8d1489ccfe18c946535952466ce3)
