### ISSUE TITLE
如何触发根路由下的子路由组件中的getInitialProps方法

### ISSUE THREAD

**Issue by wjryours** [ykfe/egg-react-ssr#164]
我设置了跟路由下的某个路由不为精确匹配然后在该路由下引入子路由组件，但是子路由组件设置getInitialProps的方法是无效的，难道我得现在根路由下拿到在传递给子组件的方式来实现吗
![image](https://user-images.githubusercontent.com/25095045/78638220-7d640080-78de-11ea-90df-7d777399f651.png)
![image](https://user-images.githubusercontent.com/25095045/78638290-9b316580-78de-11ea-801a-52679bdea883.png)
![image](https://user-images.githubusercontent.com/25095045/78638338-b0a68f80-78de-11ea-8f00-3a7cb8e4ee36.png)
我不知道我表达清楚了没，还是我的实现思路是有点问题的？

**Comment by zhangyuang** [comment]
只支持页面级路由的getInitialProps方法的调用。即请求对应的path所对应的组件。

若一定要在子组件中做数据获取，可以考虑使用suspense。默认不支持，也不建议这么做

**Comment by wjryours** [comment]
哈哈，了解了，这回复速度有点快呀
