### ISSUE TITLE
结合dva使用，添加了ConnectedRouter以后造成render两次的问题

### ISSUE THREAD

**Issue by williamnie** [ykfe/egg-react-ssr#166]
## 遇到的问题：
 在项目中使用dva，想使用dva中的routerRedux.push方法，于是在entry文件中引入了ConnectedRouter，实现了routerRedux.push的使用，但是发现会render两次。
## 尝试解决：
1.发现目前dva中使用的是connect-react-router这个包，不再是以前的react-router-redux，怀疑是connect-react-router这个包的用法有问题，

**Comment by zhangyuang** [comment]
给复现地址。
不建议用routerRedux，老老实实用history.push

**Comment by williamnie** [comment]
@zhangyuang 不好意思，忘记贴地址了，[https://github.com/williamnie/egg-ssr-dva-debug](https://github.com/williamnie/egg-ssr-dva-debug)
从老代码迁移过来的，里面很多routerRedux，改动的话太大了，想先看看有没有方法

**Comment by williamnie** [comment]
这个问题最开始是在umi的项目中发现的，一直没解决，就开始自己查问题了，用这个框架和umi进行对比，发现了这些问题，还在找问题

**Comment by zhangyuang** [comment]
你这个render两次是正常情况啊，组件本身render，以及hoc更改state之后触发子组件的render。
render多次并不是什么很奇怪的情况。

**Comment by zhangyuang** [comment]
umi跟这个的实现原理一样

**Comment by williamnie** [comment]
umi的例子里面不光是会render两次，开启getInitialProps方法后，会造成组件卸载一次，ykfe的例子就没事，怀疑还是umi有问题，您能帮忙指点下么？

**Comment by zhangyuang** [comment]
> umi的例子里面不光是会render两次，开启getInitialProps方法后，会造成组件卸载一次，ykfe的例子就没事，怀疑还是umi有问题，您能帮忙指点下么？

不要在layout里面定义getInitialProps

**Comment by williamnie** [comment]
> > umi的例子里面不光是会render两次，开启getInitialProps方法后，会造成组件卸载一次，ykfe的例子就没事，怀疑还是umi有问题，您能帮忙指点下么？
> 
> 不要在layout里面定义getInitialProps

并没有在layout里面定义，我给个例子吧，是在page里面写的

**Comment by zhangyuang** [comment]
@williamnie 不急的话可以等umi3的ssr功能发布，修复了挺多bug。急的话建议先用这个https://github.com/ykfe/ssr，目录结构跟umi的差别不大

**Comment by williamnie** [comment]
我们的项目已经在线上运行了，目前在迁移到ykfe不太好迁移，也在等3.0的ssr，如果2.0的能修一修，会减小点后端的服务器压力，目前组件会加载两次
![image](https://user-images.githubusercontent.com/26871884/80300909-15b11f00-87d3-11ea-96d7-11d794093759.png)

**Comment by williamnie** [comment]
这是个例子（压缩包），要是有时间，希望能帮忙看看，我也在查查，看看是哪里的问题，
[eggjs.zip](https://github.com/ykfe/egg-react-ssr/files/4534816/eggjs.zip)

**Comment by zhangyuang** [comment]
@williamnie 大概知道是umi源码哪块的问题，这个在umi2的设计基础上不太好解。建议等umi3或者直接用我们那个serverless ssr框架，我理解迁移成本应该很低

**Comment by williamnie** [comment]
好吧，昨天3.0的ssrdemo出来了，正在看，我们的在umi基础上又有些封装，也考虑到要升级到3.0，在迁移的话，成本有点高，可能会等3.0吧，能告诉我大概是什么原因造成的这种情况么？看了两天了，想支持为啥，🤣

**Comment by zhangyuang** [comment]
-。-我觉得你还不如把我们这个项目的源码给看明白，这个是专注于ssr的源码很清晰，umi除了ssr还有其他很多的逻辑不太好理清楚。umi的实现原理是参考我们这个的。但是因为它还包含其他的很多功能所以实际实现代码又略有不同

**Comment by williamnie** [comment]
好的，我看看这个源码，十分感谢。
