### ISSUE TITLE
vscode下删除controller下默认的api.js文件出现警告，运行无异常

### ISSUE THREAD

**Issue by wjryours** [ykfe/egg-react-ssr#167]
![image](https://user-images.githubusercontent.com/25095045/80896029-8d73d200-8d1c-11ea-9e3c-7a9f287c1ecf.png)
请问这个是因为配置的问题吗，怎么样可以去掉这个警告，强迫症看着难受，恢复这个api.js就正常了，删了就报红

**Comment by zhangyuang** [comment]
警告的内容呢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wjryours <notifications@github.com&gt;
发送时间: 2020年5月3日 09:04
收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[ykfe/egg-react-ssr] vscode下删除controller下默认的api.js文件出现警告，运行无异常 (#167)





 

 请问这个是因为配置的问题吗，怎么样可以去掉这个警告，强迫症看着难受，恢复这个api.js就正常了，删了就报红

**Comment by wjryours** [comment]
> app/controller包含强调项

并没有别的提示

**Comment by zhangyuang** [comment]
...删了就报红那你为什么要删呢，找到标红的文件肯定有具体红色代码哪一行提示你有问题啊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wjryours <notifications@github.com&gt;
发送时间: 2020年5月3日 09:29
收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt;
抄送: LeonCheung <569105585@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ykfe/egg-react-ssr] vscode下删除controller下默认的api.js文件出现警告，运行无异常 (#167)





  
app/controller包含强调项
  
并没有别的提示

**Comment by wjryours** [comment]
重点找不到标红文件呀，你也看了这个截图，他标红的只有文件夹...

**Comment by zhangyuang** [comment]
那是git的提示你删了文件。add+commit之后就没了
