### ISSUE TITLE
请问有部署的具体操作流程吗

### ISSUE THREAD

**Issue by ghost** [ykfe/egg-react-ssr#168]
刚接触egg和这个ssr框架，请问这个如果采用egg的方式部署的话是如何部署的？
因为我之前开发的自己node项目都是前后台分离的，
流程一般是
client端 打包资源通过脚本将静态文件传到cdn,然后将代码提交git 服务器拉取 跑sh脚本将service下的index.html 替换为最新的文件
 service 代码提交git ,然后服务端拉取 用pm2 reload

然后我现在看了这个框架好像执行 npm run prod命令是将客户端以及服务端的代码都进行打包，然后启动 eggctl start 命令，运行dist下js代码吗？请问用这个部署的话是怎么样的具体流程，希望能赐教

**Comment by zhangyuang** [comment]
看官方文档的部署章节。如无特殊要求。可直接生产环境执行npm run prod进行部署。若缺乏相关服务端运维经验。强烈推荐使用serverless下的ssr框架。一个命令部署。无需关注运维
https://github.com/ykfe/ssr

**Comment by zhangyuang** [comment]
@Dseekers
