### ISSUE TITLE
如何自定义页面标题？

### ISSUE THREAD

**Issue by pashangshangpo** [ykfe/egg-react-ssr#170]
![image](https://github-production-user-asset-6210df.s3.amazonaws.com/28686832/85216340-ee7f6400-b3b5-11ea-8faf-5b8496e3f558.png)

希望每个页面可以自定义title，但是layout文件下无法获取到当前页面组件的信息，比如我在news组件上面加了一个title，我怎么在layout下获取这个组件的title信息？

![image](https://github-production-user-asset-6210df.s3.amazonaws.com/28686832/85216375-651c6180-b3b6-11ea-82fa-e65c91f28d3d.png)

**Comment by zhangyuang** [comment]
title当然应该直接在layout设置，要根据页面区分的话用ctx.path



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 爬上山坡 <notifications@github.com&gt;
发送时间: 2020年6月21日 11:57
收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[ykfe/egg-react-ssr] 如何自定义页面标题？ (#170)
