### ISSUE TITLE
ykcli init 命令时，一直提示更新

### ISSUE THREAD

**Issue by Yxliam** [ykfe/egg-react-ssr#174]
ykcli init ccNav
⠙ 发现本地版本较旧,尝试更新yk-cli脚手架/Users/yxl/.nvm/versions/node/v10.19.0/bin/ykcli -> /Users/yxl/.nvm/versions/node/v10.19.0/lib/node_modules/yk-cli/lib/cli.js
+ yk-cli@3.6.18
removed 1 package and updated 1 package in 7.472s
 更新完毕... 请您重新执行 ykcli init
✔ 发现本地版本较旧,尝试更新yk-cli脚手架

**Comment by zhangyuang** [comment]
```
# yk-cli -v
3.6.18
```
保证已经安装最新版本即可

**Comment by zhangyuang** [comment]
@Yxliam 
![image](https://user-images.githubusercontent.com/17424434/87126831-75da3c00-c2bf-11ea-9bbb-d5486e3b5222.png)

**Comment by Yxliam** [comment]
<img width="486" alt="QQ20200710-161405@2x" src="https://user-images.githubusercontent.com/16329468/87132471-8511b780-c2c8-11ea-952f-5de703b87d53.png">
@zhangyuang 怎么我一直更新不到最新版本的？

**Comment by zhangyuang** [comment]
可以手动npm i -g yk-cli



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Xliam <notifications@github.com&gt;
发送时间: 2020年7月10日 16:16
收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt;
抄送: yuuang <569105585@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[ykfe/egg-react-ssr] ykcli init 命令时，一直提示更新 (#174)

**Comment by zhangyuang** [comment]
环境变量问题。。你这命令查找的路径就不对
