### ISSUE TITLE
我在windows命令行下执行 yarn start，启动 localhost 7001 ，css展示不出来，发现资源文件都是504，是哪里配置的不对吗？怎么解决？

### ISSUE THREAD

**Issue by serenaxx** [ykfe/egg-react-ssr#179]
![image](https://user-images.githubusercontent.com/7919149/88457914-9360f580-cebc-11ea-9737-8f80a60147a3.png)
![image](https://user-images.githubusercontent.com/7919149/88457993-3ca7eb80-cebd-11ea-8f7d-3bd679839dff.png)
![image](https://user-images.githubusercontent.com/7919149/88458124-3bc38980-cebe-11ea-9ab9-11236c4e24c4.png)

**Comment by serenaxx** [comment]
in windows commond

**Comment by zhangyuang** [comment]
8000 port has been used



发自我的iPhone


------------------ Original ------------------

**Comment by serenaxx** [comment]
> 8000 port has been used 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: serena <notifications@github.com&gt; Date: Sat,Jul 25,2020 8:57 PM To: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt; Cc: Subscribed <subscribed@noreply.github.com&gt; Subject: Re: [ykfe/egg-react-ssr] why my files 504 when I start localhost 7001 port? (#179) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

查了，8000端口没有被占用。。。

**Comment by zhangyuang** [comment]
截图终端启动日志。这个错的原因只可能是8000端口被其他服务占用请仔细检查



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: serena <notifications@github.com&gt;
发送时间: 2020年7月25日 21:26
收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt;
抄送: yuuang <569105585@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ykfe/egg-react-ssr] 我在windows命令行下执行 yarn start，启动 localhost 7001 ，css展示不出来，发现资源文件都是504，是哪里配置的不对吗？怎么解决？ (#179)





  
8000 port has been used 发自我的iPhone
 …
 ------------------ Original ------------------ From: serena <notifications@github.com&gt; Date: Sat,Jul 25,2020 8:57 PM To: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt; Cc: Subscribed <subscribed@noreply.github.com&gt; Subject: Re: [ykfe/egg-react-ssr] why my files 504 when I start localhost 7001 port? (#179) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
查了，8000端口没有被占用。。。

**Comment by serenaxx** [comment]
> 截图终端启动日志。这个错的原因只可能是8000端口被其他服务占用请仔细检查 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: serena <notifications@github.com&gt; 发送时间: 2020年7月25日 21:26 收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt; 抄送: yuuang <569105585@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[ykfe/egg-react-ssr] 我在windows命令行下执行 yarn start，启动 localhost 7001 ，css展示不出来，发现资源文件都是504，是哪里配置的不对吗？怎么解决？ (#179) 8000 port has been used 发自我的iPhone … ------------------ Original ------------------ From: serena <notifications@github.com&gt; Date: Sat,Jul 25,2020 8:57 PM To: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt; Cc: Subscribed <subscribed@noreply.github.com&gt; Subject: Re: [ykfe/egg-react-ssr] why my files 504 when I start localhost 7001 port? (#179) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 查了，8000端口没有被占用。。。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

已贴了截图。麻烦帮忙看看。。另外，能换端口吗？

**Comment by zhangyuang** [comment]
`FE_PORT=8001 ykcli dev`
换端口后config.local.js中端口号需一并修改

**Comment by serenaxx** [comment]
换了端口还是不行，怀疑是不支持windows cmd？目录的格式是不是不支持？所以进入不到目标目录？

**Comment by zhangyuang** [comment]
@serenaxx 不存在的，有很多windows用户之前使用过没有问题。你这个error是webpack-dev-server服务没监听成功

**Comment by serenaxx** [comment]
> @serenaxx 不存在的，有很多windows用户之前使用过没有问题。你这个error是webpack-dev-server服务没监听成功

可是我本地的确没有启动8000端口，换了8001端口依然不行的。

**Comment by zhangyuang** [comment]
额。。你是不是自己改了默认的代码啊。我还以为你跑的是默认的example。正常来说不可能会加载到Page.css以及layout.css这两个文件的

**Comment by zhangyuang** [comment]
请提供复现仓库

**Comment by serenaxx** [comment]
> 额。。你是不是自己改了默认的代码啊。我还以为你跑的是默认的example。正常来说不可能会加载到Page.css以及layout.css这两个文件的

我没有用example，就直接用的脚手架直接启动的项目，默认的config.ssr.js里就是layout.css，我只是在injectCss里面加了Page.css
![image](https://user-images.githubusercontent.com/7919149/88614105-9da01100-d0c1-11ea-889e-ca5738b11f6d.png)

**Comment by serenaxx** [comment]
我用yarn start启动的，不用npm 也是可以的吧？

**Comment by zhangyuang** [comment]
默认的脚手架项目也不可能有layout.css和page.css。。。

**Comment by serenaxx** [comment]
![image](https://user-images.githubusercontent.com/7919149/88614208-d344fa00-d0c1-11ea-9980-897ef89e09d6.png)
这个也是默认的脚本配置

**Comment by serenaxx** [comment]
求解决。。

**Comment by zhangyuang** [comment]
please分清楚page.css和page.chunk.css的区别。请提供复现仓库。不要修改默认的ininjectcss配置

**Comment by serenaxx** [comment]
> 默认的脚手架项目也不可能有layout.css和page.css。。。

![image](https://user-images.githubusercontent.com/7919149/88614299-07b8b600-d0c2-11ea-89ea-ea1b6306beb7.png)
你们readme里面的引导里的配置

**Comment by zhangyuang** [comment]
那是page.chunk.css。。。

**Comment by serenaxx** [comment]
> 那是page.chunk.css。。。

对，但我看dist目录里生成的文件是page.css并没有page.chunk.css，所以改成了page.css，而且p是大写的

**Comment by serenaxx** [comment]
> > 那是page.chunk.css。。。
> 
> 对，但我看dist目录里生成的文件是page.css并没有page.chunk.css，所以改成了page.css，而且p是大写的

![image](https://user-images.githubusercontent.com/7919149/88614427-51090580-d0c2-11ea-8ce4-920ed12fe6d3.png)

**Comment by zhangyuang** [comment]
本地开发在内存里面dist目录里面当然没有。。。

**Comment by serenaxx** [comment]
> 本地开发在内存里面dist目录里面当然没有。。。

额 那为什么dist里面有page.css啊。。

**Comment by zhangyuang** [comment]
。。请阅读文档这不是你现在要关心的事情

**Comment by zhangyuang** [comment]
不要访问layout.css以及page.css这两个文件8000服务下根本没有这两个文件😓please 访问http://127.0.0.1:7001/static/js/Page.chunk.js or http://127.0.0.1:8000/static/js/Page.chunk.js。如果不行那就是你自己的服务没起来

**Comment by serenaxx** [comment]
> 额。。你是不是自己改了默认的代码啊。我还以为你跑的是默认的example。正常来说不可能会加载到Page.css以及layout.css这两个文件的

我没有用example，就直接用的脚手架和readme里面的指引

**Comment by serenaxx** [comment]
> 不要访问layout.css以及page.css这两个文件8000服务下根本没有这两个文件😓please 访问http://127.0.0.1:7001/static/js/Page.chunk.js or [http://127.0.0.1:8000/static/js/Page.chunk.js。如果不行那就是你自己的服务没起来](http://127.0.0.1:8000/static/js/Page.chunk.js%E3%80%82%E5%A6%82%E6%9E%9C%E4%B8%8D%E8%A1%8C%E9%82%A3%E5%B0%B1%E6%98%AF%E4%BD%A0%E8%87%AA%E5%B7%B1%E7%9A%84%E6%9C%8D%E5%8A%A1%E6%B2%A1%E8%B5%B7%E6%9D%A5)

![image](https://user-images.githubusercontent.com/7919149/88614803-1ce21480-d0c3-11ea-85d0-e4b1a90f0a2e.png)
socket连接不上？但是我就是直接脚手架启动的啊，为什么不行呢

**Comment by zhangyuang** [comment]
不行是你自己的机器服务问题，跟脚手架没关系

**Comment by serenaxx** [comment]
从启动的编译log看，依然没有.chunk文件
![image](https://user-images.githubusercontent.com/7919149/88615363-5d8e5d80-d0c4-11ea-971f-126dd0c94bfb.png)

**Comment by zhangyuang** [comment]
那是服务端bundle当然没有chunk文件。。算了我更新发个版优化一下客户端的输出日志吧

**Comment by serenaxx** [comment]
> 那是服务端bundle当然没有chunk文件。。算了我更新发个版优化一下客户端的输出日志吧

我发现我直接访问本地8000是可以访问到这个文件的，
![image](https://user-images.githubusercontent.com/7919149/88615611-df7e8680-d0c4-11ea-87d7-e0042f7cadcf.png)
但是，直接本地7001就是连接不到8000的这个文件了
![image](https://user-images.githubusercontent.com/7919149/88615657-fc1abe80-d0c4-11ea-9471-6f003c825c63.png)

**Comment by zhangyuang** [comment]
那就是egg-proxy 把7001的服务转发到8000的出的问题。。应该是机器自身的原因

**Comment by zhangyuang** [comment]
please update to `yk-cli@3.6.21`

**Comment by serenaxx** [comment]
本地代理的原因，已解决
