### ISSUE TITLE
切换路由/list/1、/list/2不走getInitialProps

### ISSUE THREAD

**Issue by guojun158** [ykfe/egg-react-ssr#180]
1、切换路由 http://127.0.0.1:7001/list/1 和http://127.0.0.1:7001/list/2，不走Page.getInitialProps = async (ctx) => {}方法。
2、只有切换不同的路由地址，比如：（/list、/）才能走getInitialProps
3、目前的需求是，在同一路由地址下，只是后面的参数不同，比如：
/list/1?pageIndex=1&pageSize=20&owner=1&keyword=&category=1&labels=17 这个路由下，需要变化不同的参数值通过csr渲染来获取出不同的数据出来，返回给页面。
4、希望给出具体解决方案来。

**Comment by zhangyuang** [comment]
给复现仓库

**Comment by zhangyuang** [comment]
https://segmentfault.com/q/1010000009309279
同一组件切换没有触发组件的卸载以及挂载的过程。自然也不会触发getInitialProps。
参考该文章解答
