### ISSUE TITLE
client端需要获取url上的参数数据id，用到location.pathname，但server端不能解析window，怎么解决？

### ISSUE THREAD

**Issue by serenaxx** [ykfe/egg-react-ssr#181]
报错：
nodejs.ReferenceError: location is not defined，
在component里怎么获取route上params？

**Comment by serenaxx** [comment]
报错：
nodejs.ReferenceError: location is not defined
--

**Comment by zhangyuang** [comment]
服务端参考egg文档使用ctx.req.params.xxx ctx.req.xxx

**Comment by zhangyuang** [comment]
服务端参考egg文档使用ctx.req.params.xxx ctx.req.xxx

**Comment by serenaxx** [comment]
我在entry.js里把ctx.req.url 传给了ActiveComponent，已解决
