### ISSUE TITLE
在layout里引入公共header组件，在组件的getInitialProps的方法里，如何使用mapDispatchToProps的dispatch 方法获取数据？

### ISSUE THREAD

**Issue by serenaxx** [ykfe/egg-react-ssr#182]
layout里引入公共header组件，在组件的getInitialProps的方法里，如何使用mapDispatchToProps的dispatch 方法获取数据？

**Comment by serenaxx** [comment]
![image](https://user-images.githubusercontent.com/7919149/89166860-398fb800-d5ad-11ea-9ea8-784061b32588.png)
没有触发请求

**Comment by zhangyuang** [comment]
常规上建议不要在layout里面做获取数据的逻辑！
如有需要自行修改serverentry方法

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: serena <notifications@github.com&gt;
发送时间: 2020年8月3日 17:17
收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[ykfe/egg-react-ssr] 在layout里引入公共header组件，在组件的getInitialProps的方法里，如何使用mapDispatchToProps的dispatch 方法获取数据？ (#182)

**Comment by serenaxx** [comment]
> serverentry的修改有例子吗？

**Comment by serenaxx** [comment]
获取公共info数据 肯定要写在layout里，要不然每个页面初始化都要请求一遍。

**Comment by serenaxx** [comment]
![image](https://user-images.githubusercontent.com/7919149/89169341-ae182600-d5b0-11ea-9634-dfe1c1044191.png)
controller里面请求数据吗，还是？

**Comment by zhangyuang** [comment]
如有需要自行修改entry文件。follow bigpipe思想layout不应该用于获取数据



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: serena <notifications@github.com&gt;
发送时间: 2020年8月3日 17:41
收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt;
抄送: yuuang <569105585@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ykfe/egg-react-ssr] 在layout里引入公共header组件，在组件的getInitialProps的方法里，如何使用mapDispatchToProps的dispatch 方法获取数据？ (#182)

**Comment by zhangyuang** [comment]
follow默认示例的写法就行了...唯一要做的只是支持layout.getInitialProps而已



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: serena <notifications@github.com&gt;
发送时间: 2020年8月3日 17:43
收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt;
抄送: yuuang <569105585@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ykfe/egg-react-ssr] 在layout里引入公共header组件，在组件的getInitialProps的方法里，如何使用mapDispatchToProps的dispatch 方法获取数据？ (#182)

**Comment by serenaxx** [comment]
> follow默认示例的写法就行了...唯一要做的只是支持layout.getInitialProps而已 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: serena <notifications@github.com&gt; 发送时间: 2020年8月3日 17:43 收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt; 抄送: yuuang <569105585@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[ykfe/egg-react-ssr] 在layout里引入公共header组件，在组件的getInitialProps的方法里，如何使用mapDispatchToProps的dispatch 方法获取数据？ (#182)

哦，类似于这个吧？
![image](https://user-images.githubusercontent.com/7919149/89169793-4c0bf080-d5b1-11ea-8a37-5773e14ccfbe.png)

**Comment by serenaxx** [comment]
layout也要执行一次getinitialprops，已解决
