### ISSUE TITLE
在clientRender里的BrowserRouter上加basename参数，会报错，有遇到过吗？怎么解决

### ISSUE THREAD

**Issue by serenaxx** [ykfe/egg-react-ssr#185]
![image](https://user-images.githubusercontent.com/7919149/89261721-22120700-d661-11ea-8647-4e9c3803794f.png)

**Comment by zhangyuang** [comment]
客户端的服务端的dom渲染结果不匹配不要拿spa的思想来开发

**Comment by serenaxx** [comment]
已在entry里做了处理
