### ISSUE TITLE
example只有mobx的例子，有redux相关的示例代码吗？最好是redux+multipage的例子

### ISSUE THREAD

**Issue by serenaxx** [ykfe/egg-react-ssr#186]

**Comment by zhangyuang** [comment]
不推荐用redux。redux只会让你的应用变得更复杂
同时不推荐用multipage，没有深厚的webpack经验multipage只会让你的应用构建配置变得更复杂且难以开发

**Comment by serenaxx** [comment]
> 不推荐用redux。redux只会让你的应用变得更复杂
> 同时不推荐用multipage，没有深厚的webpack经验multipage只会让你的应用构建配置变得更复杂且难以开发

。。。你之前不是说不要拿spa的思想来开发吗，那不是mpa更好些吗，而且本来我项目用的redux redux-thunk+spa模式的，现在想对项目同构ssr，准备改为mpa+redux的ssr，请教下，有其他好的推荐吗？本身项目还是挺复杂的

**Comment by zhangyuang** [comment]
......你根本就没有理解我那句话的意思。扫码加群吧

**Comment by serenaxx** [comment]
> ......你根本就没有理解我那句话的意思。扫码加群吧

有二维码吗 扫下

**Comment by zhangyuang** [comment]
请仔细阅读readme

**Comment by serenaxx** [comment]
multipage+redux已经加了，已解决
