### ISSUE TITLE
请教下，client端默认的压缩配置没有生效，该怎么解决

### ISSUE THREAD

**Issue by serenaxx** [ykfe/egg-react-ssr#188]

**Comment by zhangyuang** [comment]
为什么要改minimize呢，基础问题请查看webpack文档

**Comment by serenaxx** [comment]
> 为什么要改minimize呢，基础问题请查看webpack文档

就是想做压缩和加hash，有相关的例子可以参考吗？谢谢

> 默认就已经压缩了。。hash查一下文档的output就可以了啊。。。随手就能google到答案的问题不会单独提供例子

。。。默认给出的压缩并没有生效啊 hash加上会报错啊，要不然我问你干嘛

**Comment by zhangyuang** [comment]
默认就已经压缩了。。hash查一下文档的output就可以了啊。。。随手就能google到答案的问题不会单独提供例子
