### ISSUE TITLE
请问如何使用 localstorage 之类的 bom？

### ISSUE THREAD

**Issue by rottenpen** [ykfe/egg-react-ssr#196]
在 page 里面使用 window localstorage 之类的，都会在服务端先跑，然后报错 window is not defined

**Comment by zhangyuang** [comment]
参考 http://ykfe.surge.sh/guide/faq.html#%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%E6%9C%8D%E5%8A%A1%E7%AB%AF%E8%AE%BF%E9%97%AE%E4%B8%8D%E5%8F%AF%E8%AE%BF%E9%97%AE%E7%9A%84%E5%AF%B9%E8%B1%A1%E7%9A%84%E9%97%AE%E9%A2%98
