### ISSUE TITLE
脚手架问题

### ISSUE THREAD

**Issue by LuvFishBone** [ykfe/egg-react-ssr#199]
全局安装了 ykcli --version 有版本号？
为什么ykcli init react-ssr-test 不能创建项目，什么反应都没有？

**Comment by zhangyuang** [comment]
看readme ykcli init 已经废除改为换了种创建方式



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: FishBone <notifications@github.com&gt;
发送时间: 2020年11月10日 13:49
收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[ykfe/egg-react-ssr] 脚手架问题 (#199)





 
全局安装了 ykcli --version 有版本号？
 为什么ykcli init react-ssr-test 不能创建项目，什么反应都没有？

**Comment by LuvFishBone** [comment]
谢谢答复！
刚使用命令
`npm init ssr-app my-ssr-project --template=ssr-with-js`
等了很久然后提示
`fatal: unable to access 'https://github.com/ykfe/egg-react-ssr.git/'`

**Comment by zhangyuang** [comment]
网络问题吧连不上github



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: FishBone <notifications@github.com&gt;
发送时间: 2020年11月10日 14:01
收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt;
抄送: yuuang <569105585@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ykfe/egg-react-ssr] 脚手架问题 (#199)

**Comment by LuvFishBone** [comment]
我试了好几次 都是这样，应该不是网络问题，谢谢大佬，我再试试。

**Comment by zhangyuang** [comment]
![image](https://user-images.githubusercontent.com/17424434/98634809-e2914000-235e-11eb-86d7-150b2d467191.png)

**Comment by LuvFishBone** [comment]
嗯 我每次都是这样，应该是我们公司网络做了限制
<img width="650" alt="截屏2020-11-10下午2 19 50" src="https://user-images.githubusercontent.com/42053296/98635381-d6f24900-235f-11eb-934c-5b05004a8222.png">

**Comment by zhangyuang** [comment]
也可以直接clone这个项目来跑example

**Comment by LuvFishBone** [comment]
好的，最近在研究服务端渲染，刚好看到你们这个开源项目。👍
