### ISSUE TITLE
浏览器端接手数据怎么获取

### ISSUE THREAD

**Issue by LuvFishBone** [ykfe/egg-react-ssr#200]
请教一个问题，首次服务端获取数据渲染以后，点击链接到另外一个路由，再返回以后数据没有渲染，需要做什么处理么？如下图
<img width="894" alt="截屏2020-11-14下午5 48 07" src="https://user-images.githubusercontent.com/42053296/99144585-f65fdd80-26a1-11eb-93fc-5c6b82f9bc12.png">

**Comment by zhangyuang** [comment]
官方example已经包含了路由pop的场景。请自行对照
