### ISSUE TITLE
打包的文件是否支持Hash。如何解决浏览器缓存问题。

### ISSUE THREAD

**Issue by Link-Kou** [ykfe/egg-react-ssr#203]
单页面的时候，打包出来的文件都带有hash
解决缓存起来也比较方便
我在想打包的文件是否支持Hash。比如不支持，有什么比较好的解决浏览器缓存问题。

**Comment by feibinyang** [comment]
默认生成的配置就支持把，`output` 配置项

**Comment by zhangyuang** [comment]
默认不生成hash，想要生成可以修改下webpack的output配置即可。不过生成后每次生产环境发布需要手动在config中更新最新的hash
