### ISSUE TITLE
钉钉二维码已过期

### ISSUE THREAD

**Issue by Baoyx007** [ykfe/egg-react-ssr#204]

**Comment by zhangyuang** [comment]
收到晚点更新下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Haven <notifications@github.com&gt;
发送时间: 2020年12月13日 18:16
收件人: ykfe/egg-react-ssr <egg-react-ssr@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[ykfe/egg-react-ssr] 钉钉二维码已过期 (#204)

**Comment by zhangyuang** [comment]
已更新
