### ISSUE TITLE
getIntialProps里对象嵌套对象会失效，是只能用平级数据嘛

### ISSUE THREAD

**Issue by xiaokyo** [ykfe/egg-react-ssr#206]
![image](https://user-images.githubusercontent.com/22857964/102784933-0fae2500-43d8-11eb-80db-6258e1782d27.png)
服务端是没问题的，客户端切路由到这个页面 这样写会报错

![image](https://user-images.githubusercontent.com/22857964/102784975-205e9b00-43d8-11eb-9c6c-e6e8d99a41a3.png)
这样是好的

**Comment by xiaokyo** [comment]
第一张图的写法，在切路由的时候，会取不到整个name的值

**Comment by zhangyuang** [comment]
应该是业务代码自己的问题，getIntialProps做的事情很简单你返回什么就给props注入什么。与是否嵌套无关

**Comment by xiaokyo** [comment]
是业务的问题。解决了
