### ISSUE TITLE
按照官网教程来安装，启动就报错了，模板是 nestjs-react-ssr

### ISSUE THREAD

**Issue by zaleGZL** [ykfe/egg-react-ssr#217]
![image](https://user-images.githubusercontent.com/20339327/126853316-3eb44692-3d03-46ef-9362-21e8969351ca.png)

**Comment by zhangyuang** [comment]
swiper这个模块前几天升级了，锁定版本6.7.5或者重新创建demo已解决



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 郭泽凌 ***@***.***&gt;
发送时间: 2021年7月24日 09:12
收件人: ykfe/egg-react-ssr ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ykfe/egg-react-ssr] 按照官网教程来安装，启动就报错了，模板是 nestjs-react-ssr (#217)

**Comment by zaleGZL** [comment]
> swiper这个模块前几天升级了，锁定版本6.7.5或者重新创建demo已解决 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 郭泽凌 ***@***.***&gt; 发送时间: 2021年7月24日 09:12 收件人: ykfe/egg-react-ssr ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[ykfe/egg-react-ssr] 按照官网教程来安装，启动就报错了，模板是 nestjs-react-ssr (#217) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，谢谢～
