### ISSUE TITLE
ssr-with-js template 启动不正确

### ISSUE THREAD

**Issue by luffyZh** [ykfe/egg-react-ssr#218]
按照教程安装访问直接是下图：
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/17840558/190983811-bb6bb0ef-9e9a-4ddf-b543-8be355806692.png">
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/17840558/190983865-d9558406-1c99-4a45-a87a-2e2cf32114f7.png">

**Comment by zhangyuang** [comment]
访问7001， and 不要再使用 egg-react-ssr 用 https://github.com/zhangyuang/ssr
