### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Panamer** [ykfe/egg-react-ssr#25]
Page Controller renderToStream Error TypeError: config.injectScript is not a function

**Comment by zhangyuang** [comment]
> Page Controller renderToStream Error TypeError: config.injectScript is not a function

请升级到最新版本的ykfe-utils，之前这个config.injectScript我们拼写错了为injectSrcipt,在最新版本中我们已经为这两种写法都做了兼容。或者你可以将config.default.js中injectScript拼写正确

**Comment by Panamer** [comment]
thanks
