### ISSUE TITLE
关于yk-cli@1.0.13相关问题

### ISSUE THREAD

**Issue by ihubcode** [ykfe/egg-react-ssr#29]
**现存问题及优化建议：**

1. js-sass版本在init过程，一直在“下载模版中...”，其实中断构建过程，运行项目是可以的，有待优化；

2. 为了提高脚手架使用体验，建议在init完成后，新增初始化项目运行命令指南，例如:
`
 npm install
 npm run  start
`
而且注意到js与ts版本开发环境启动命令尚不同，能否统一，或者直接在脚手架初始化时做出命令指南，就不用去阅读package.json中脚本配置。只是建议，考虑下

**Comment by zhangyuang** [comment]
> **现存问题及优化建议：**
> 
> 1. js-sass版本在init过程，一直在“下载模版中...”，其实中断构建过程，运行项目是可以的，有待优化；
> 2. 为了提高脚手架使用体验，建议在init完成后，新增初始化项目运行命令指南，例如:
>    ` npm install  npm run  start`
>    而且注意到js与ts版本开发环境启动命令尚不同，能否统一，或者直接在脚手架初始化时做出命令指南，就不用去阅读package.json中脚本配置。只是建议，考虑下

嗯，脚手架的代码今天会重构完成。
ts版本的话我们会先隐藏，ts的负责同学最近业务较忙，我们先建议使用js的版本。等ts版本我们完善完毕后再提供ts的选项

**Comment by zhangyuang** [comment]
> **现存问题及优化建议：**
> 
> 1. js-sass版本在init过程，一直在“下载模版中...”，其实中断构建过程，运行项目是可以的，有待优化；
> 2. 为了提高脚手架使用体验，建议在init完成后，新增初始化项目运行命令指南，例如:
>    ` npm install  npm run  start`
>    而且注意到js与ts版本开发环境启动命令尚不同，能否统一，或者直接在脚手架初始化时做出命令指南，就不用去阅读package.json中脚本配置。只是建议，考虑下

@ihubcode yk-cli@1.0.14已发布，欢迎使用提出建议

**Comment by zhangyuang** [comment]
> **现存问题及优化建议：**
> 
> 1. js-sass版本在init过程，一直在“下载模版中...”，其实中断构建过程，运行项目是可以的，有待优化；
> 2. 为了提高脚手架使用体验，建议在init完成后，新增初始化项目运行命令指南，例如:
>    ` npm install  npm run  start`
>    而且注意到js与ts版本开发环境启动命令尚不同，能否统一，或者直接在脚手架初始化时做出命令指南，就不用去阅读package.json中脚本配置。只是建议，考虑下

yk-cli@1.0.14版本已发布，欢迎使用提出建议
