### ISSUE TITLE
支持单个小组件的getInitialProps方法的调用

### ISSUE THREAD

**Issue by zhangyuang** [ykfe/egg-react-ssr#34]
目前getInitialProps只支持路由级别的大组件才会被调用，next.js也是这样。
如果可以支持定义每一个小组件也使用getInitialProps来定义获取数据的逻辑，我们就可以精细的控制一个组件的获取数据以及渲染的过程，到底要在服务端做还是在客户端做。可以根据实际需求，来让需要优先展示的模块放在服务端渲染，次级模块在客户端渲染。将性能做到极致

**Comment by YaoKaiLun** [comment]
所以目前支持了吗？嵌套路由的情况挺需要的

**Comment by zhangyuang** [comment]
这个目前还不支持像next.js这些框架目前也不支持，有思路但是最近没什么时间开发，有兴趣可以贡献PR。可扫码加钉钉群沟通

**Comment by zhangyuang** [comment]
@YaoKaiLun 嵌套路由的数据获取比较简单，可以参考https://juejin.im/post/5c20cb3e6fb9a049de6d623f
单个任意小组件的比较复杂，不过看你们的需求只需要支持嵌套路由的话可以参考那篇文章来实现
