### ISSUE TITLE
接下来的规划

### ISSUE THREAD

**Issue by zhangyuang** [ykfe/egg-react-ssr#37]
# 现状

目前本应用能够通过脚手架新建比较稳定的运行，目前该配置可以解决大部分项目的基本需求，但为了应付灵活多变的需求，我们还需要不断的完善本应用所支持的场景，目前初步列出以下待办事项

## 数据流

提供结合多种流行的数据管理方式的example

- [x] 结合dva的example
- [x] 结合mobx的example

## 组件到达时间统计

服务端渲染应用的首屏时间是一个很难通过浏览器提供的API来直观看出的数据，我们必须在应用中手动触发时间统计埋点，如何让开发者做到无感知的给应用组件中添加时间统计的埋点也是一项有价值的任务，以上一个页面的unload时间为基准，即performance.timing.navigationStart的时间，目前只支持页面级别的组件信息统计

- [ ] 当前应用在服务端的一些性能监控数据
- [ ] 显示该组件在服务端被渲染完毕的时间
- [ ] 显示该组件在浏览器中出现的时间

## 结合loadable

将bundle能够根据路由来分割能够进一步的加快首屏domContentLoaded的时间，不过对首屏时间的影响不大，但loadable结合SSR应用定义的getInitialProps方法来作为数据获取的方法，并没有那么简单，需要修改react-loadable源码

- [x] 结合loadable进行路由分割(example已发布，但仍有完善空间

## 更细粒度的组件获取

我们目前的getInitalProps方法只支持在路由级别的"大"组件中调用生效，如果能够支持在每一个更小粒度的组件也是通过该方法去获取数据，那我们就可以更精细的控制一个组件的渲染逻辑，究竟要放在服务端还是客户端。将首屏性能做到极致

- [ ] getInitalProps方法支持更细粒度的组件

## 多页面应用

目前给的example是单页面应用，如果要做多页面应用实质上是多个entry分别打包为单独的bundle，但如何做到配置更加灵活，更加轻便是个不小的难题，以及需要讨论既然ssr已经解决了seo的问题，就解决了多页面应用的一个优势。ssr + 路由分割理论上已经足够好用了，而多页面应用的缺点却很多，所以得考虑当前应用究竟有没有必要做成多页面应用的必要。
- [ ] 讨论是否需要支持多页面应用

## 添加测试

- [x] 单元测试
- [x] ci
- [x] e2e测试

## ts化

- [x] ykfe-utils 使用ts重写

**Comment by Bigerfe** [comment]
大佬  https://github.com/Bigerfe/koa-react-ssr 我写了一个 koa 的 ssr

**Comment by dazjean** [comment]
对于多页面应用的支持的讨论有结果了吗？您提到多页面应用的缺点很多，能否介绍一下相关的讨论呢？

**Comment by zhangyuang** [comment]
主要在于多页应用配置复杂，且无明显优点。如果要做大规模的多页应用我建议是每个页面独立应用部署而不是放在一个应用当中。例如优酷首页和播放页是独立的两个应用
