### ISSUE TITLE
Windows下运行异常问题

### ISSUE THREAD

**Issue by deancn175** [ykfe/egg-react-ssr#38]
经测试，项目在非Windows环境（Mac、Ubuntu）运行正常。但在windows环境下，由于Windows command无法正常设置NODE_ENV，会阻塞退出，导致webpack无法正常生成dist目录文件，因此无法正常运行项目。如下图：

![image](https://user-images.githubusercontent.com/48011106/60232985-ff93b300-98d0-11e9-91d0-2c16ae41504d.png)

解决方法：package.json脚本新增cross-env 抹平运行环境兼容问题

**Comment by zhangyuang** [comment]
欢迎pr

**Comment by i5ting** [comment]
@deancn175 再改一下吧，加油
