### ISSUE TITLE
ssr中使用hooks报错

### ISSUE THREAD

**Issue by zhangyuang** [ykfe/egg-react-ssr#4]
![image](https://user-images.githubusercontent.com/17424434/59035159-40367880-889f-11e9-9305-c896165df847.png)
在ssr应用中使用react hooks会报上图错误。
查了一下原因是因为出现了多个实例的react-dom。发现将renderToStream方法移动到项目中就没事了。
查了一下类似的问题挺多的。[#14898](https://github.com/facebook/react/issues/14898) [#13972](https://github.com/facebook/react/issues/13972)

**Comment by zhangyuang** [comment]
已修复，为了保证当前使用的react-dom是同一个。在第三方模块的renderToStream方法中从项目目录的node_modules中读取react-dom,而不是从第三方模块自己的node_modules中读取

**Comment by JayaZhu** [comment]
> 已修复，为了保证当前使用的react-dom是同一个。在第三方模块的renderToStream方法中从项目目录的node_modules中读取react-dom,而不是从第三方模块自己的node_modules中读取
> 
> ```
>  if (!global.renderToNodeStream) {
>     const ReactDOMServer = require(config.baseDir + '/node_modules/react-dom/server')
>     const { renderToNodeStream } = ReactDOMServer
>     global.renderToNodeStream = renderToNodeStream
>   }
> ```

useful for me
