### ISSUE TITLE
ykcli init 报错

### ISSUE THREAD

**Issue by dddddd1** [ykfe/egg-react-ssr#41]
node 版本 v10.15.1

`(node:92402) UnhandledPromiseRejectionWarning: undefined
(node:92402) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:92402) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by zhangyuang** [comment]
> node 版本 v10.15.1
> 
> `(node:92402) UnhandledPromiseRejectionWarning: undefined (node:92402) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:92402) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

请提供yk-cli版本号

**Comment by dddddd1** [comment]
npm install yk-cli -g  显示的是 1.0.16

然后重新init后   发现本地版本较旧,尝试更新yk-cli脚手架变成  yk-cli@1.0.15
然后就好了 谢谢

**Comment by zhangyuang** [comment]
> npm install yk-cli -g 显示的是 1.0.16
> 
> 然后重新init后 发现本地版本较旧,尝试更新yk-cli脚手架变成 yk-cli@1.0.15
> 然后就好了 谢谢

可以扫码进入dingding群，那里可以收到及时反馈
