### ISSUE TITLE
debug 重启时会有缓存，我该如何清理呢。

### ISSUE THREAD

**Issue by robert7git** [ykfe/egg-react-ssr#42]

**Comment by robert7git** [comment]
删掉 dist , build -> debug.
可不可以有自动清理功能。

**Comment by zhangyuang** [comment]
> 删掉 dist , build -> debug.
> 可不可以有自动清理功能。

你指的缓存是哪个文件的缓存

**Comment by robert7git** [comment]
就是 yarn debug ->  关闭 -> yarn debug.
"debug": "npm run build:server && egg-bin debug"
加了个 命令似乎 还好。
谢谢回复
