### ISSUE TITLE
关于dva 中 routerRedux 跳转不生效问题 （url 变了 ，页面没更新）

### ISSUE THREAD

**Issue by Tanzhiling** [ykfe/egg-react-ssr#54]
在dva effect中使用routerRedux提供的push api，可以跳转页面，但无法触发页面的生命周期调用

```
store.dispatch(push('/'))
```

**Comment by zhangyuang** [comment]
# 原因
dva 的routerRedux实际引用的是`react-router-redux`这个库，观察这个库源码可知，这个库中的history来源是connectedRouter这个组件的props.history，故如果不使用connectedRouter将入口组件包一层并且传入history，在`react-router-redux`将无法获取到正确的history

# 解决方式
![](https://img.alicdn.com/tfs/TB1EN_rbAY2gK0jSZFgXXc5OFXa-1530-1220.png)

**Comment by williamnie** [comment]
您好，当我按照图片这种方式修改以后，发现了一个问题，首次打开页面，会造成render两次，貌似是history变化了，导致刷新了，您对这个有什么好的建议或者解决方案么？@zhangyuang

**Comment by zhangyuang** [comment]
@williamnie 新开一个issue给复现仓库。个人建议老老实实用history.push pop这些api最好。图片贴的方法只是给想用routerRedux的人用，我是不建议这么写的

**Comment by williamnie** [comment]
@zhangyuang  已经提了新的issue [https://github.com/ykfe/egg-react-ssr/issues/166](https://github.com/ykfe/egg-react-ssr/issues/166)
