### ISSUE TITLE
关于 webpack output 配置的疑问

### ISSUE THREAD

**Issue by maoyuyang** [ykfe/egg-react-ssr#67]
你好，看文档的时候有一个疑惑，为什么output的 `filename` 和 `chunkFilename` 只使用了 `[name]` , 而没有用 `[contenthash]` / `[chunkhash]` 等。

打包出来的名称没有变化，会不会导致因为缓存而让用户无法得到最新的文件？如果是使用协商缓存，那好像强缓存会更好一点，hash值变了就重新获取，协商还要来回通信

所以这部分的考量是什么呢？

**Comment by FrankFan** [comment]
同问，我就遇到了这个问题，部署后客户端浏览器无法拉取到最新的代码，被缓存了

**Comment by FrankFan** [comment]
@maoyuyang  请问是怎么解决的？ 看到你把这个issue给close了

**Comment by zhangyuang** [comment]
> @maoyuyang 请问是怎么解决的？ 看到你把这个issue给close了

用版本号来控制静态资源的版本，或者自行添加hash。不建议用hash值
详细流程看[最佳发布实践](http://ykfe.net/guide/deploy.html)

**Comment by zhangyuang** [comment]
hash值的问题：
- 没办法追溯版本
- 没办法方便的通过配置文件来手动设置要加载的静态资源，需要额外增加从从assetManifest.json中获取当前构建最新的hash值自动注入的逻辑。
