### ISSUE TITLE
egg-react-ssr/example/ssr-with-antd/例子中build:client和build:server写入css文件造成覆盖

### ISSUE THREAD

**Issue by and80506** [ykfe/egg-react-ssr#68]
现象：
egg-react-ssr/example/ssr-with-antd/项目中，

build:client
![popo_2019-08-28  20-50-56](https://user-images.githubusercontent.com/1769410/63857229-e93fcb80-c9d5-11e9-9f97-2f2f479ae769.jpg)
build:server
![f765543acd434c81a35b33fb1416b0ec_09b651fea17fe6a03afad39a41422bfa](https://user-images.githubusercontent.com/1769410/63857243-f066d980-c9d5-11e9-9180-60917b587dfa.jpg)

`3.chunk.css`被覆盖了

初步分析：
```js
// package.json
{
    "build": "rimraf dist && ykcli build && npm run build:server",
}
```
同时调用了webpack.config.base.js先后写入css文件，造成覆盖
```js
//  build/webpack.config.base.js    
new MiniCssExtractPlugin({
      filename: 'static/css/[name].css',
      chunkFilename: 'static/css/[name].chunk.css'
})
```

**Comment by zhangyuang** [comment]
并不会写入覆盖哈，server端和client端生成的文件名都不一样。一个是Page.css,一个是Page.chunk.css, 理论上这个两个文件内容是一样的，你只需要用到Page.chunk.css就够了。不知道你的1.chunk.css是哪来的，我们的example是没有做css分块的，我也不建议你去做css分块
