### ISSUE TITLE
injectScript支持类似webpack的[contenthash]

### ISSUE THREAD

**Issue by and80506** [ykfe/egg-react-ssr#69]
现象：
目前injectScript引入script时未带url查询参数或更新文件名，造成发布后http强缓存。
`<script src='/static/js/Page.chunk.js'></script>`
建议：
支持类似webpack的[contenthash]
`<script src='/static/js/Page.chunk.[contenthash].js'></script>`

**Comment by Tanzhiling** [comment]
@and80506  可以去改下静态资源的配置 egg-static的 默认缓存时间是1年
![image](https://user-images.githubusercontent.com/31690439/63919628-b64b1580-ca71-11e9-86f1-380f546a835a.png) 改webpack 作用不大 尤其是本地开发时 重新编译 就会生成一个新的hash值

**Comment by zhangyuang** [comment]
静态资源的发布方式有两种
1、通过cdn单独发布，如果有cdn资源的话，我是建议用文件夹加版本号来做缓存更新，而不是用过hash值这种方式。你的加载的静态文件资源路径都是通过config来控制的，如果你要用hash做缓存更新，就改一下webpack生成带有hash值的文件，当然我不推荐你这么做，因为替换起来比较麻烦，也不好追溯版本
2、通过自己的Node静态资源目录发布，就像 @Tanzhiling 所说的，不要让egg缓存你的静态资源，或者也可以通过版本号的方式来生成一个新文件，并修改config里面的路径微信的版本号，如下
```
injectScript: [
    `<script src='http://cdn/1.0.0/static/js/runtime~Page.js'></script>`,
    `<script src='http://cdn/1.0.0/static/js/vendor.chunk.js'></script>`,
    `<script src='http://cdn/1.0.0/static/js/Page.chunk.js'></script>`
  ], // 客户端需要加载的静态资源文件表
```

**Comment by i5ting** [comment]
确认一下是否已经加到文档里了

**Comment by hansinhu** [comment]
读取 manifest.json 方式解决
// webpack.client.js - plugins
```
new WebpackAssetsManifest({
      .....
      done () {
        const p = path.resolve(__dirname, 'dist', 'manifest.json')
        const helper = ent => _.flow([
          _.partial(fs.readFileSync),
          _.partial(JSON.parse),
          _.partial(_.get, _, ent),
        ])(p)
        const assets = helper('assets')

        const injectCss = assets
          .filter(item => /.css$/.test(item))

        const injectScript = assets
          .filter(item => /.js$/.test(item))
          .map(item => `<script src="${item}"></script>`)

        const injectConfig = path.resolve(__dirname, 'config', 'inject.json')
        fs.writeFileSync(injectConfig, JSON.stringify({
            injectCss,
            injectScript,
          }))
      },
    }),

```
```
// config.ssr.js
const injectConfig = require('./inject.json')
module.exports = {
  type: 'ssr',
  routes: [],
  injectCss: injectConfig.injectCss,
  injectScript: injectConfig.injectScript,
  ....
}
```

**Comment by zhangyuang** [comment]
@hansinhu 如果一定要用hash的话可以用这种形式。
提几点建议
1、可以封装成一个插件，仅接收一个数组用来控制文件的加载顺序例如`new Plugin(['vendor', 'runtime', 'page'])`。还需要考虑多页面的情况就会略有复杂
2、加上错误处理，如果我的inject.json还未生成访问页面会不会报错

综上如果要使用hash可以采用这种方式来避免手动粘贴hash值，但不建议使用hash来做版本控制，理由已经说过了。不利于版本追溯以及用起来麻烦。可以封完之后给文档提个PR写个FAQ

**Comment by i5ting** [comment]
@hansinhu 来个pr吧，需要的话可以找 @zhangyuang 小哥哥帮忙
