### ISSUE TITLE
是否支持远程加载静态资源文件

### ISSUE THREAD

**Issue by HadeAs** [ykfe/egg-react-ssr#83]
目前示例里的前端页面代码都是放在`web/page`目录下的。通过config.ssr.js中的这块代码
`Component: () => (require('@/page/index').default)`去加载。
但是现在有一种场景就是，这些前端代码都是单独部署的独立应用，是否可以提供一种机制去加载这些独立应用编译打包后的js，css文件 @zhangyuang

**Comment by HadeAs** [comment]
核心意思就是egg-react-ssr提供一个门户框架的功能，门户下面的每一个菜单都是对应一个独立部署的子应用，通过这个框架去加载这些子应用，以及子应用之间的切换

**Comment by zhangyuang** [comment]
可以扫码加入钉钉群详聊。
不太建议你去这么做，这样有几种缺陷，一个是割裂了前端代码和Node代码，不好维护，出问题很难调试。还有一个是已经部署好的前端应用build后都是umd格式而不是cmd格式，没办法直接导出一个组件。需要更改构建方式。而且你的组件是需要被webpack.server.js去构建一遍生成服务端bundle的，如果文件不在本地的话比较难搞。

目前看来把一个react项目迁移到我们这套方案的成本是很低的，直接把前端组件复制过来加上静态方法就行了

有想法的话可以加群私聊，你可以尝试去实现一下，欢迎pr

**Comment by HadeAs** [comment]
> 可以扫码加入钉钉群详聊。
> 不太建议你去这么做，这样有几种缺陷，一个是割裂了前端代码和Node代码，不好维护，出问题很难调试。还有一个是已经部署好的前端应用build后都是umd格式而不是cmd格式，没办法直接导出一个组件。需要更改构建方式。而且你的组件是需要被webpack.server.js去构建一遍生成服务端bundle的，如果文件不在本地的话比较难搞。
> 
> 目前看来把一个react项目迁移到我们这套方案的成本是很低的，直接把前端组件复制过来加上静态方法就行了
> 
> 有想法的话可以加群私聊，你可以尝试去实现一下，欢迎pr

了解，感谢解答
