### ISSUE TITLE
CSR的一些疑问

### ISSUE THREAD

**Issue by HadeAs** [ykfe/egg-react-ssr#84]
我本地yarn csr  开启客户端渲染
查看界面元素发现这些资源文件：
![20190925095846](https://user-images.githubusercontent.com/12652964/65563117-2074ae80-df7b-11e9-8f90-b845775aa828.jpg)
但是看代码逻辑是不包含这些资源文件的啊：
![20190925095707](https://user-images.githubusercontent.com/12652964/65563158-400bd700-df7b-11e9-81ec-5fc47aa21a7f.jpg)
不知道是不是我哪里没理解清楚？ @zhangyuang

**Comment by zhangyuang** [comment]
csr的页面模版是会用else里面的那套的，你csr实际是用webpack-dev-server给你起了一个express，在你访问express服务的时候__isBrowser__这个变量是false。会先用这个else里面的内容给你吐出一个页面模版。
ssr的时候同理，先用else里面的内容给你吐一个页面模版，if里面的内容是客户端真正hydrate的元素节点部分。
其实就相当于你用其他框架的脚手架比如cra和vue-cli里面的index.html文件变成了下面的else语句里面的内容

**Comment by HadeAs** [comment]
> csr的页面模版是会用else里面的那套的，你csr实际是用webpack-dev-server给你起了一个express，在你访问express服务的时候__isBrowser__这个变量是false。会先用这个else里面的内容给你吐出一个页面模版。
> ssr的时候同理，先用else里面的内容给你吐一个页面模版，if里面的内容是客户端真正hydrate的元素节点部分。
> 其实就相当于你用其他框架的脚手架比如cra和vue-cli里面的index.html文件变成了下面的else语句里面的内容

好的 感谢解答
