### ISSUE TITLE
ykcli: command not found（ykcli 命令无法使用）

### ISSUE THREAD

**Issue by panzhengtao** [ykfe/egg-react-ssr#85]
windows下面，npm i -g yk-cli 安装成功：
![image](https://user-images.githubusercontent.com/20961522/65743256-6326ba00-e126-11e9-996e-a9b727dcdf66.png)
然后添加至环境变量：
![image](https://user-images.githubusercontent.com/20961522/65743309-979a7600-e126-11e9-87fa-157bc34204d0.png)
然后ykcli仍无法使用：
![image](https://user-images.githubusercontent.com/20961522/65743364-ce708c00-e126-11e9-934b-236da0e4a440.png)

**Comment by zhangyuang** [comment]
https://ykfe.net/guide/faq.html#%E6%89%BE%E4%B8%8D%E5%88%B0ykcli%E5%91%BD%E4%BB%A4%E6%80%8E%E4%B9%88%E5%8A%9E

请按照该步骤来排查错误

**Comment by i5ting** [comment]
@zhangyuang 确认发布了就close了
