### ISSUE TITLE
框架的TS支持库怎么没有文档……

### ISSUE THREAD

**Issue by scott-leung** [ykfe/egg-react-ssr#86]
如题。

我看仓库列表中有相应的项目，但是没有文档……难以入坑

**Comment by zhangyuang** [comment]
ts的项目主要有哪一块不太清楚呢？目前负责ts的同学比较忙文档暂时没时间完善？有时间ts的example也会好好重新打磨的

**Comment by scott-leung** [comment]
对……就是ts没有example，现在基本都用ts了。。。不过也可以先入坑看看^_^

**Comment by zhangyuang** [comment]
> 对……就是ts没有example，现在基本都用ts了。。。不过也可以先入坑看看^_^

正在补充

**Comment by i5ting** [comment]
在整理基于midway的实现，稍后放出来

**Comment by zhangyuang** [comment]
@scott-leung https://github.com/ykfe/egg-react-ssr/tree/dev/example/ssr-with-ts

已添加ts版本的实现

**Comment by scott-leung** [comment]
> @scott-leung https://github.com/ykfe/egg-react-ssr/tree/dev/example/ssr-with-ts
> 
> 已添加ts版本的实现

收到~看看去~

**Comment by jerryYuX** [comment]
现在已经基本完成了基于midway的实现和对typeScript的支持，实现思路大致如下：
首先把node服务端替换为midway,并在保持框架原有特性的情况，拓展midway的新特性（例如支持路由装饰器，inject依赖注入等），同时前端react替换为typeScript版本。
