### ISSUE TITLE
获取数据报错

### ISSUE THREAD

**Issue by LBC100** [ykfe/egg-react-ssr#91]
报错信息
![image](https://user-images.githubusercontent.com/38514123/67085385-4b949b80-f1d1-11e9-892f-14171e8a3581.png)
触发获取数据
![image](https://user-images.githubusercontent.com/38514123/67085418-5ea76b80-f1d1-11e9-88a2-5056c01ed2ec.png)
models:
![image](https://user-images.githubusercontent.com/38514123/67085530-8f87a080-f1d1-11e9-860b-ede62415fff7.png)

**Comment by zhangyuang** [comment]
![image](https://user-images.githubusercontent.com/17424434/67085656-cd84c480-f1d1-11e9-96b6-3a2c6d8465e3.png)
原因给你写的很清楚了直接去google，学会基本的搜索bug能力

**Comment by LBC100** [comment]
另一个示范: 在componentDidMount 里获取
![image](https://user-images.githubusercontent.com/38514123/67085729-f311ce00-f1d1-11e9-964c-c2bca3636be3.png)


结果:
![image](https://user-images.githubusercontent.com/38514123/67085655-cc539780-f1d1-11e9-80c6-b0c9f41df1d0.png)

**Comment by i5ting** [comment]
@LBC100 看一下文档，获取数据用的是getInitialProps方法

```
function Page(props) {
  return <div> {props.name} </div>
}

Page.getInitialProps = async (ctx) => {
  return Promise.resolve({
    name: 'Egg + React + SSR'
  })
}

export default Page
```

**Comment by i5ting** [comment]
@LBC100 目前看是没问题的，如果还有问题，给个最小可复现仓库吧

**Comment by wzw1992071** [comment]
getInitialProps里面应该咋办呢
