### ISSUE TITLE
bug: 执行npm run csr报错

### ISSUE THREAD

**Issue by yxbgithub1** [ykfe/egg-react-ssr#95]
报错-Error: Invariant failed: You should not use <Link> outside a <Router>

**Comment by zhangyuang** [comment]
给最小复现

**Comment by yxbgithub1** [comment]
首先我非常喜欢你们的脚手架，项目结构简洁干净，同时支持ts，我想要的实现是部分路由是ssr，其他部分是csr-spa
1. 运行npm run csr会失败，报错Invariant failed: You should not use <Link> outside a <Router>(抱歉，昨天复制错误)，我所知道的是因为路由嵌套问题
2. 文档中提到__isBrowser__ 切换ssr和csr，但是因为第一步失败，导致无法研究剩下的实现

**Comment by i5ting** [comment]
@yxbgithub1 好的，我们查一下

**Comment by zhangyuang** [comment]
> 首先我非常喜欢你们的脚手架，项目结构简洁干净，同时支持ts，我想要的实现是部分路由是ssr，其他部分是csr-spa
> 
> 1. 运行npm run csr会失败，报错Invariant failed: You should not use  outside a (抱歉，昨天复制错误)，我所知道的是因为路由嵌套问题
> 2. 文档中提到__isBrowser__ 切换ssr和csr，但是因为第一步失败，导致无法研究剩下的实现

给一个复现的仓库地址。你那个错我知道是什么原因是因为多个react-router实例冲突，这个错误我在很早的版本就修复了不知道你是不是改了什么代码导致出错
__isBrowser__ 不是切换ssr/csr的只是一个标志环境变量而已
不支持路由级别的渲染模式模式定制，你通过config.type可以指定整个项目的渲染模式

**Comment by Zero2key** [comment]
我也遇到了这个问题，直接用 `ykcli init` 生成的 `typescript` 项目，没有改动任何代码，运行 `npm run csr` 报错 `Error: Invariant failed: You should not use <Link> outside a <Router>`。

环境:
mac os 10.14.6
node 12.12.0
yk-cli 2.7.2

**Comment by zhangyuang** [comment]
@Zero2key @yxbgithub1 ts的example看了一下确实有问题，已修复，可以看看commit具体改了哪个地方新的复制过去即可。或者重新init一遍项目
